<HTML>
<HEAD>
<meta charset="UTF-8">
<title>fails - Assert4K</title>
<link rel="stylesheet" href="../../style.css">
</HEAD>
<BODY>
<a href="../index.html">Assert4K</a>&nbsp;/&nbsp;<a href="index.html">assert4k</a>&nbsp;/&nbsp;<a href="./fails.html">fails</a><br/>
<br/>
<h1>fails</h1>
<a name="assert4k$fails(kotlin.Function0((kotlin.Unit)))"></a>
<code><span class="keyword">fun </span><span class="identifier">fails</span><span class="symbol">(</span><span class="identifier" id="assert4k$fails(kotlin.Function0((kotlin.Unit)))/block">block</span><span class="symbol">:</span>&nbsp;<span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="-assertion-continuation.html"><span class="identifier">AssertionContinuation</span></a><span class="symbol">&lt;</span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">&gt;</span></code>
<p>Asserts that given function <a href="fails.html#assert4k$fails(kotlin.Function0((kotlin.Unit)))/block">block</a> fails by throwing an exception.
<code> assert that fails { throw Exception() } </code></p>
<p><strong>Return</strong><br/>
An exception that was expected to be thrown and was successfully caught.
The returned exception can be inspected further, for example by asserting its property values.</p>
</BODY>
</HTML>
